# Generated by Django 4.2.4 on 2023-08-15 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('submit', models.CharField(default='Submit', max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'text'), ('PASSWORD', 'passowrd'), ('NUMBER', 'number'), ('EMAIL', 'email'), ('FILE', 'file'), ('TEXTAREA', 'textarea')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('placeholder', models.CharField(blank=True, max_length=40)),
                ('max_len', models.CharField(blank=True, max_length=20)),
                ('min_len', models.CharField(blank=True, max_length=20)),
                ('rows', models.CharField(blank=True, max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formApp.form')),
            ],
            options={
                'ordering': ['-position'],
            },
        ),
    ]
