# Generated by Django 4.2.4 on 2023-08-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='max_len',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='min_len',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='rows',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
