# Generated by Django 4.2.4 on 2023-08-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_alter_field_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['position']},
        ),
    ]
